services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env # Diese Datei wird gelesen und ihre Variablen stehen den Containern zur Verfügung

#  db:
#    image: mariadb:10.6
#    ports:
#      - "3307:3306"
#    environment:
#      MYSQL_DATABASE: dataBaseEduco
#      MYSQL_USER: newUser
#      MYSQL_PASSWORD: password
#      MYSQL_ROOT_PASSWORD: password
#    volumes:
#      - ./mysql:/var/lib/mysql
