services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  react:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    volumes:
      - .:/app
    depends_on:
      - laravel

  db:
    image: mariadb:10.6
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: dataBaseEduco
      MYSQL_USER: newUser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
